#pragma once
enum SceneState
{
	NO_SCENE,
	START_SCENE,
	PLAY_SCENE,
	ESCAPE_SCENE_VER1,
	ESCAPE_SCENE_VER2,
	ESCAPE_SCENE_VER3,
	STORY_SCENE,
	DEATH_SCENE_VER1,
	DEATH_SCENE_VER2,
	DEATH_SCENE_VER3,
	NUM_OF_SCENE
};